<?php
$parameters = array(
	'cache_path' => '%kernel.root_dir%/cache',
	'log_path' => '%kernel.root_dir%/logs',
	'site_url' => 'http://89.212.49.138',
	'install_source' => 'Mautic',
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'optera2',
	'db_user' => 'root',
	'db_password' => '1ftrp007',
	'db_path' => null,
	'mailer_from_name' => 'Sandra Koren Kuhar',
	'mailer_from_email' => '',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => 'a8c04a7a31aea296975151d58f878926296a2e6a40dfd6c9d14aee55699e2e78',
);
