<?php
$parameters = array(
	'cache_path' => '%(root)s/cache',
	'log_path' => '%(root)s/logs',
	'site_url' => 'http://%(domain)s',
	'install_source' => 'Mautic',
	'db_driver' => '%(db_driver)s',
	'db_host' => '%(db_host)s',
	'db_table_prefix' => null,
	'db_port' => '%(db_port)s',
	'db_name' => '%(db_name)s',
	'db_user' => '%(db_user)s',
	'db_password' => '%(db_password)s',
	'db_path' => null,
	'mailer_from_name' => '%(mailer_from_name)s',
	'mailer_from_email' => '',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%(root)s/spool',
	'secret_key' => 'a8c04a7a31aea296975151d58f878926296a2e6a40dfd6c9d14aee55699e2e78',
);
