#!/bin/sh

GUNICORN=/usr/local/bin/gunicorn
ROOT=%(project_dir)s
PID=/var/run/gunicorn.pid

APP=%(app)s:application

if [ -f $PID ]; then rm $PID; fi

cd $ROOT
exec $GUNICORN -c $ROOT/gunicorn.conf.py --pid=$PID $APP