mautic:
  #image: mautic/mautic #this version 1.2.4
  image: worldevops/mautic:2.2.1 #this version 2.2.1
  links:
    - mauticdb:mysql
  ports:
    - 82:80
  restart: always

mauticdb:
  image: mysql:5.6
  volumes:
       - "./.data/db:/var/lib/mysql"
  restart: always
  environment:
       MYSQL_ROOT_PASSWORD: {{mapass}}
       MYSQL_DATABASE: mautic
       MYSQL_USER: root
       MYSQL_PASSWORD: {{mapass}}

